# Generated by Django 5.2 on 2025-05-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                db_index=True,
                default="open",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
