# Generated by Django 5.2 on 2025-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_issue_status_alter_issue_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="summary_html",
            field=models.TextField(blank=True, null=True),
        ),
    ]
