# Generated by Django 5.2 on 2025-05-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_issue_summary_html"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="created_by",
            new_name="author",
        ),
    ]
