# Generated by Django 5.2 on 2025-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_rename_created_by_issue_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueactivity",
            name="content_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issueactivity",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
