# Generated by Django 6.1 on 2026-08-23 04:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=128, unique=True)),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=128)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
