# Generated by Django 5.2 on 2025-05-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="resource",
            field=models.FileField(blank=True, upload_to="projects_resources/"),
        ),
    ]
