# Generated by Django 5.2 on 2025-05-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_open_pull_requests_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="merged_pull_requests_count",
            field=models.IntegerField(default=0),
        ),
    ]
