# Generated by Django 5.2 on 2025-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="resource_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="project",
            name="handle",
            field=models.SlugField(blank=True, max_length=128),
        ),
    ]
