# Generated by Django 5.2 on 2025-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_resource_version_alter_project_handle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="resource_version",
        ),
        migrations.AddField(
            model_name="project",
            name="resource_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
