# Generated by Django 5.2 on 2025-05-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_resource_version_project_resource_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="open_issues_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="total_issues_count",
            field=models.IntegerField(default=0),
        ),
    ]
