# Generated by Django 5.2 on 2025-05-18 10:29

from django.db import migrations


def populate_owner_username(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    for project in Project.objects.select_related("owner").all():
        project.owner_username = project.owner.username
        project.save(update_fields=["owner_username"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_owner_username"),
    ]

    operations = [
        migrations.RunPython(populate_owner_username, migrations.RunPython.noop),
    ]
