# Generated by Django 5.2.5 on 2025-09-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_activated_at_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
