# Generated by Django 5.2.5 on 2025-09-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_activation_clicks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verified_at",
        ),
    ]
