# Generated by Django 5.2.5 on 2025-09-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_verified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="activation_clicks",
        ),
    ]
