# Generated by Django 5.2 on 2025-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="attached_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
