# Generated by Django 5.2 on 2025-05-16 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_open_pull_requests_count_and_more"),
        ("pull_requests", "0002_pullrequestactivity_pullrequestassignee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("project", "source_branch", "target_branch"),
                name="unique_open_pull_request_per_branch_pair",
            ),
        ),
    ]
