# Generated by Django 5.2 on 2025-05-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pull_requests", "0003_pullrequest_unique_open_pull_request_per_branch_pair"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pullrequest",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed"), ("merged", "Merged")],
                db_index=True,
                default="open",
                max_length=32,
            ),
        ),
    ]
