# Generated by Django 6.1 on 2026-08-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_onboarded", models.BooleanField(default=False)),
                ("organization_name", models.CharField(max_length=128)),
                ("support_email_address", models.EmailField(max_length=128)),
                ("application_url", models.URLField(blank=True, null=True)),
                ("allow_login", models.BooleanField(default=True)),
                ("allow_new_user", models.BooleanField(default=True)),
                ("is_2fa_mandatory", models.BooleanField(default=False)),
                ("maintaince_mode", models.BooleanField(default=False)),
                ("maintaince_message", models.TextField(blank=True, null=True)),
                ("banner_message", models.TextField(blank=True, null=True)),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("banner_expiry", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "config",
            },
        ),
    ]
