# Generated by Django 6.1 on 2026-08-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="smtp_default_from_email",
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="smtp_email_host",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="smtp_email_port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="smtp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="config",
            name="smtp_encryption",
            field=models.CharField(
                blank=True,
                choices=[("TLS", "TLS"), ("SSL", "SSL")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="smtp_host_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="smtp_host_user",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
