# Generated by Django 5.2.5 on 2025-08-30 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("handle", models.SlugField(blank=True, max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        max_length=12,
                    ),
                ),
                ("default_branch", models.CharField(default="main", max_length=128)),
                ("website", models.URLField(blank=True, null=True)),
                ("total_issues_count", models.IntegerField(default=0)),
                (
                    "repository",
                    models.FileField(blank=True, null=True, upload_to="repositories/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("owner_user__isnull", False)),
                        fields=("handle", "owner_user"),
                        name="unique_user_project_handle",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("owner_org__isnull", False)),
                        fields=("handle", "owner_org"),
                        name="unique_org_project_handle",
                    ),
                ],
            },
        ),
    ]
