# Generated by Django 6.1 on 2026-08-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="repo_count",
            new_name="repository_count",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="repo_default_branch",
            new_name="repository_default_branch",
        ),
    ]
