# Generated by Django 5.2.5 on 2025-09-03 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_user_project_handle",
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_org_project_handle",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="handle",
            new_name="slug",
        ),
        migrations.AddField(
            model_name="project",
            name="namespace",
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner_user__isnull", False)),
                fields=("slug", "owner_user"),
                name="unique_user_project_handle",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner_org__isnull", False)),
                fields=("slug", "owner_org"),
                name="unique_org_project_handle",
            ),
        ),
    ]
