# Generated by Django 5.2 on 2025-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="open_pull_requests_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="total_pull_requests_count",
            field=models.IntegerField(default=0),
        ),
    ]
