# Generated by Django 5.2.5 on 2025-09-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_unique_user_project_handle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="namespace",
            field=models.SlugField(blank=True, max_length=512, unique=True),
        ),
    ]
