# Generated by Django 6.1 on 2026-08-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_repo_count_project_repository_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="event_count",
            field=models.IntegerField(default=0),
        ),
    ]
