# Generated by Django 5.2 on 2025-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_merged_pull_requests_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner_username",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
