# Generated by Django 5.2.5 on 2025-09-05 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectpermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborations",
                through="projects.ProjectPermission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
