# Generated by Django 5.2 on 2025-05-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_auto_20250518_1029"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="owner_username",
            new_name="owner_handle",
        ),
    ]
