# Generated by Django 5.2.5 on 2025-09-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_collaborators"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="repository",
        ),
    ]
