# Generated by Django 5.2 on 2025-05-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_rename_owner_username_project_owner_handle"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_handle",
        ),
    ]
