# Generated by Django 5.2 on 2025-05-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_project_unique_project_handle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="handle",
            new_name="project_handle",
        ),
    ]
