# Generated by Django 5.2 on 2025-05-20 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_rename_handle_project_project_handle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("owner_handle", "project_handle"),
                name="unique_project_handle_per_owner",
            ),
        ),
    ]
