# Generated by Django 5.2 on 2025-05-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_unique_project_handle_per_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owner_handle",
            field=models.SlugField(blank=True, max_length=128),
        ),
    ]
