# Generated by Django 5.2 on 2025-05-21 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_project_owner_handle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_handle_per_owner",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="owner_handle",
            new_name="namespace",
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("namespace", "project_handle"),
                name="unique_project_handle_per_owner",
            ),
        ),
    ]
