# Generated by Django 5.2 on 2025-05-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_remove_project_unique_project_handle_per_owner_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_handle_per_owner",
        ),
    ]
