# Generated by Django 5.2 on 2025-05-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_remove_project_unique_project_handle_per_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_handle",
            new_name="handle",
        ),
    ]
