# Generated by Django 5.2 on 2025-05-21 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_rename_project_handle_project_handle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("namespace", "handle"), name="unique_project_handle_per_owner"
            ),
        ),
    ]
