# Generated by Django 5.2 on 2025-05-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_project_unique_project_handle_per_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="owner",
            new_name="user",
        ),
    ]
