# Generated by Django 5.2 on 2025-05-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_project_created_by"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_handle_per_owner",
        ),
    ]
