# Generated by Django 5.2 on 2025-05-24 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_members"),
        ("projects", "0020_alter_project_namespace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("namespace", "handle"), name="unique_project_handle_per_owner"
            ),
        ),
    ]
