# Generated by Django 5.2 on 2025-05-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="issueactivity",
            table="issue_activities",
        ),
        migrations.AlterModelTable(
            name="issueassignee",
            table="issue_assignees",
        ),
    ]
