# Generated by Django 5.2 on 2025-05-27 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issueactivity_table_alter_issueassignee_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='summary_html',
        ),
    ]
