# Generated by Django 5.2 on 2025-05-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_issue_summary_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueactivity',
            name='content_html',
        ),
    ]
