# Generated by Django 5.2 on 2025-05-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pull_requests', '0004_alter_pullrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequest',
            name='description_html',
        ),
        migrations.RemoveField(
            model_name='pullrequestactivity',
            name='content_html',
        ),
    ]
