# Generated by Django 5.2 on 2025-06-01 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pull_requests", "0005_remove_pullrequest_description_html_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="assignees",
            field=models.ManyToManyField(
                related_name="pull_requests_assigned",
                through="pull_requests.PullRequestAssignee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
