# Generated by Django 6.0.3 on 2026-04-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitRef",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=40, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("short_name", models.CharField(blank=True, max_length=256)),
                (
                    "ref_type",
                    models.CharField(
                        choices=[
                            ("branch", "Branch"),
                            ("tag", "Tag"),
                            ("remote", "Remote"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_sha", models.CharField(max_length=40)),
                ("is_head", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_refs",
                        to="gitsap.project",
                    ),
                ),
            ],
            options={
                "db_table": "git_refs",
                "indexes": [
                    models.Index(
                        fields=["project", "ref_type"],
                        name="git_refs_project_c3103a_idx",
                    ),
                    models.Index(
                        fields=["project", "short_name"],
                        name="git_refs_project_cc6777_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "name"), name="uniq_gitref_project_name"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_head", True)),
                        fields=("project",),
                        name="uniq_gitref_single_head_per_project",
                    ),
                ],
            },
        ),
    ]
