# Generated by Django 6.0.3 on 2026-04-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0002_create_git_refs_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitCommit",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=40, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sha", models.CharField(max_length=40)),
                ("message", models.TextField()),
                ("author_name", models.CharField(max_length=255)),
                ("author_email", models.EmailField(max_length=254)),
                ("author_time", models.DateTimeField()),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True, related_name="children", to="gitsap.gitcommit"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_commits",
                        to="gitsap.project",
                    ),
                ),
            ],
            options={
                "db_table": "git_commits",
                "indexes": [
                    models.Index(
                        fields=["project", "author_time"],
                        name="git_commits_project_aee3fa_idx",
                    ),
                    models.Index(
                        fields=["author_email"], name="git_commits_author__c36e18_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "sha"), name="uniq_gitcommit_project_sha"
                    )
                ],
            },
        ),
    ]
