# Generated by Django 6.0.3 on 2026-04-08 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0003_gitcommit"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitFileChange",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=40, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("modified", "Modified"),
                            ("deleted", "Deleted"),
                            ("renamed", "Renamed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_path", models.TextField(null=True)),
                ("new_path", models.TextField(null=True)),
                ("additions", models.IntegerField(default=0)),
                ("deletions", models.IntegerField(default=0)),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commit_file_changes",
                        to="gitsap.gitcommit",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_file_changes",
                        to="gitsap.project",
                    ),
                ),
            ],
            options={
                "db_table": "git_file_changes",
            },
        ),
    ]
