# Generated by Django 6.0.3 on 2026-04-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0004_gitfilechange"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gitcommit",
            name="git_commits_project_aee3fa_idx",
        ),
        migrations.RemoveIndex(
            model_name="gitcommit",
            name="git_commits_author__c36e18_idx",
        ),
        migrations.RemoveConstraint(
            model_name="gitcommit",
            name="uniq_gitcommit_project_sha",
        ),
        migrations.RemoveField(
            model_name="gitfilechange",
            name="commit",
        ),
        migrations.RemoveField(
            model_name="gitfilechange",
            name="project",
        ),
        migrations.RemoveIndex(
            model_name="gitref",
            name="git_refs_project_c3103a_idx",
        ),
        migrations.RemoveIndex(
            model_name="gitref",
            name="git_refs_project_cc6777_idx",
        ),
        migrations.RemoveConstraint(
            model_name="gitref",
            name="uniq_gitref_project_name",
        ),
        migrations.RemoveConstraint(
            model_name="gitref",
            name="uniq_gitref_single_head_per_project",
        ),
        migrations.RemoveField(
            model_name="gitcommit",
            name="parents",
        ),
        migrations.RemoveField(
            model_name="gitcommit",
            name="project",
        ),
        migrations.DeleteModel(
            name="GitFileChange",
        ),
        migrations.RemoveField(
            model_name="gitref",
            name="project",
        ),
        migrations.DeleteModel(
            name="GitCommit",
        ),
        migrations.DeleteModel(
            name="GitRef",
        ),
    ]
