# Generated by Django 6.0.3 on 2026-04-10 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0005_remove_gitcommit_git_commits_project_aee3fa_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitRepository",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="git_repository",
                        serialize=False,
                        to="gitsap.project",
                    ),
                ),
                (
                    "repo_path",
                    models.CharField(blank=True, max_length=512, unique=True),
                ),
                ("is_empty", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "git_repositories",
            },
        ),
    ]
