# Generated by Django 6.0.3 on 2026-04-10 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0006_gitrepository"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitrepository",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gitrepository",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
