# Generated by Django 6.0.3 on 2026-04-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0007_gitrepository_created_at_gitrepository_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="git_repo_path",
        ),
    ]
