# Generated by Django 6.0.3 on 2026-04-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0008_remove_project_git_repo_path"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gitrepository",
            table="repositories",
        ),
    ]
