# Generated by Django 6.0.3 on 2026-04-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0009_alter_gitrepository_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GitRepository",
            new_name="Repository",
        ),
    ]
