# Generated by Django 6.0.3 on 2026-04-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0010_rename_gitrepository_repository"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="repository",
                serialize=False,
                to="gitsap.project",
            ),
        ),
    ]
