# Generated by Django 6.0.3 on 2026-04-10 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitsap", "0011_alter_repository_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=40, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("slug", models.SlugField(blank=True, max_length=256, unique=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="OrganizationPermission",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=40, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("maintainer", "Maintainer"),
                            ("collaborator", "Collaborator"),
                            ("viewer", "Viewer"),
                        ],
                        default="collaborator",
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="gitsap.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organization_permissions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"),
                        name="uniq_user_permission_per_org",
                    )
                ],
            },
        ),
    ]
