# Generated by Django 5.2 on 2025-06-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0003_alter_pipeline_triggered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinestep",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=32,
            ),
        ),
    ]
