# Generated by Django 5.2 on 2025-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0004_pipelinestep_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipelinestep",
            name="status",
        ),
        migrations.AddField(
            model_name="pipelinejob",
            name="log_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pipelinejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
