# Generated by Django 5.2 on 2025-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pipelines",
            "0005_remove_pipelinestep_status_pipelinejob_log_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinejob",
            name="ignore_failure",
            field=models.BooleanField(default=False),
        ),
    ]
