# Generated by Django 5.2 on 2025-06-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0006_pipelinejob_ignore_failure"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinejob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pipelinejob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
